### PR TITLE
Add coala sprint

### PR DESCRIPTION
**Pull request by sils**
CC @fneu who'll be there

### CODE REVIEW

**Comment by ThomasWaldmann** [comment]
hmm, would be cool if someone would actually merge the PRs. ;-)

**Comment by sils** [comment]
@ThomasWaldmann you can write a GitMate plugin for that: http://docs.gitmate.io/Developers/Writing_Plugin/

This'll run hosted on GitMate.io and do the job for you.

As for the sprint, @fneu couldn't attend the conference after all so I guess it's better to not merge this.

**Comment by ThomasWaldmann** [comment]
@sils you mean a pluggin for nagging about unmerged PRs?

**Comment by sils** [comment]
or a plugin that automerges them

Sincerely,

Lasse Schuirmann

lasse@schuirmann.net
Founder of http://coala.io/, http://viperdev.io/ and http://gitmate.io/

**Pull request closed without merging**
